  wdqs-updater:
    image: wikibase/wdqs:0.3.0
    build:
      context: ./wdqs/0.3.0
      dockerfile: Dockerfile
    command: /runUpdate.sh
    depends_on:
    - wdqs
    - wikibase
    networks:
      default:
        aliases:
         - wdqs-updater.svc