version: '2'
services:
    graphite-statsd:
        image: hopsoft/graphite-statsd
        environment:
         - VIRTUAL_HOST=graphite.mw.localhost
        volumes:
         - graphite-data:/opt/graphite/storage

volumes:
    graphite-data:
