  wdqs-proxy:
    image: wikibase/wdqs-proxy
    build:
      context: ./wdqs-proxy/latest
      dockerfile: Dockerfile
    environment:
      - PROXY_PASS_HOST=wdqs.svc:9999
    ports:
     - "8989:80"
    depends_on:
    - wdqs
    networks:
      default:
        aliases:
         - wdqs-proxy.svc